import { Router } from "express";
import { authRouter } from "./auth/auth.routes.js";
import { companiesRouter } from "./companies/companies.routes.js";
import { companyLicenseRouter, licensesRouter } from "./licenses/licenses.routes.js";
import { usersRouter } from "./users/users.routes.js";
import { groupsRouter, screensRouter } from "./screens/screens.routes.js";
import { playerRouter } from "./player/player.routes.js";
import { mediaRouter } from "./media/media.routes.js";
import { playlistsRouter } from "./playlists/playlists.routes.js";
import { schedulesRouter } from "./schedules/schedules.routes.js";
import { layoutsRouter } from "./layouts/layouts.routes.js";
import { templateInstancesRouter, templatesRouter } from "./templates/templates.routes.js";
import { offersRouter } from "./offers/offers.routes.js";
import { campaignsRouter, winnersRouter } from "./campaigns/campaigns.routes.js";
import { notificationsRouter } from "./notifications/notifications.routes.js";
import { activityRouter } from "./activity/activity.routes.js";
import { canvasRouter } from "./canvas/canvas.routes.js";

/** Mounts every domain router under /api/v1. Modules are added here as they are built. */
export const apiRouter = Router();
apiRouter.use("/auth", authRouter);
apiRouter.use("/companies/:companyId/license", companyLicenseRouter);
apiRouter.use("/companies", companiesRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/licenses", licensesRouter);
apiRouter.use("/screens", screensRouter);
apiRouter.use("/screen-groups", groupsRouter);
apiRouter.use("/player", playerRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/playlists", playlistsRouter);
apiRouter.use("/schedules", schedulesRouter);
apiRouter.use("/layouts", layoutsRouter);
apiRouter.use("/templates", templatesRouter);
apiRouter.use("/template-instances", templateInstancesRouter);
apiRouter.use("/offers", offersRouter);
apiRouter.use("/campaigns", campaignsRouter);
apiRouter.use("/winners", winnersRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/activity", activityRouter);
apiRouter.use("/canvas", canvasRouter);
